name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.3

dependencies:
  artemis_custom_gen:
    path: ..

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^2.0.0
  test: ^1.21.0
