name: artemis_custom_gen
description: Custom types generator for artemis.
version: 0.1.0
repository: https://github.com/lapuske/artemis_custom_gen

environment:
  sdk: ^3.1.0

dependencies:
  analyzer: ">=5.0.0 <8.0.0"
  build: ^2.4.0
  build_runner: ^2.4.4
  dart_style: ^3.1.0
  glob: ^2.1.2
  source_gen: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0